<?php

declare(strict_types=1);

namespace CastorRecipes;

use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\Installer\PackageEvent;
use Composer\Installer\PackageEvents;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;
use Symfony\Component\Filesystem\Filesystem;

final class Plugin implements PluginInterface, EventSubscriberInterface
{
    private Composer $composer;

    private IOInterface $io;

    public function activate(Composer $composer, IOInterface $io): void
    {
        $this->composer = $composer;
        $this->io = $io;
    }

    public function deactivate(Composer $composer, IOInterface $io): void
    {
        // no-op
    }

    public function uninstall(Composer $composer, IOInterface $io): void
    {
        // no-op
    }

    public static function getSubscribedEvents(): array
    {
        return [
            PackageEvents::POST_PACKAGE_INSTALL => 'onPostPackageInstall',
            PackageEvents::POST_PACKAGE_UPDATE => 'onPostPackageUpdate',
        ];
    }

    public function onPostPackageInstall(PackageEvent $packageEvent): void
    {
        $operation = $packageEvent->getOperation();
        $package = method_exists($operation, 'getPackage') ? $operation->getPackage() : null;
        if (! $package) {
            return;
        }

        if ($package->getName() !== 'raffaelecarelle/castor-recipes') {
            return; // only act when this package gets installed
        }

        $this->runInstaller();
    }

    public function onPostPackageUpdate(PackageEvent $packageEvent): void
    {
        $operation = $packageEvent->getOperation();
        $package = method_exists($operation, 'getTargetPackage') ? $operation->getTargetPackage() : null;
        if (! $package) {
            return;
        }

        if ($package->getName() !== 'raffaelecarelle/castor-recipes') {
            return; // only act when this package gets updated (freshly required)
        }

        $this->runInstaller();
    }

    private function runInstaller(): void
    {
        $vendorDir = $this->composer->getConfig()->get('vendor-dir');
        $projectRoot = \dirname((string) $vendorDir);

        $recipes = [
            'symfony',
            'laravel',
            'shopware6',
            'orocommerce',
            'magento2',
            'wordpress',
        ];

        $this->io->write('<info>Castor Recipes</info>: choose a recipe to install.');
        $choice = $this->io->select('Which recipe do you want to install?', $recipes, '0');
        $recipe = $recipes[$choice] ?? 'symfony';

        $relativeRequirePath = 'vendor/raffaelecarelle/castor-recipes/recipes/' . $recipe . '.php';
        $castorFile = $projectRoot . '/castor.php';

        $filesystem = new Filesystem();

        if (! $filesystem->exists($castorFile)) {
            $content = <<<PHP
<?php
// Generated by raffaelecarelle/castor-recipes
// You can add more recipes with additional require lines.

require __DIR__ . '/$relativeRequirePath';

PHP;
            $filesystem->dumpFile($castorFile, $content);
            $this->io->write(sprintf('<info>Created</info> %s with recipe <comment>%s</comment>.', $this->relativeToCwd($castorFile), $recipe));
        } else {
            $this->io->write('<comment>castor.php already exists in your project.</comment>');
            $this->io->write('Manually add the following line to your <info>castor.php</info> to include the recipe:');
            $this->io->write('');
            $this->io->write(sprintf("    require __DIR__ . '/%s';", $relativeRequirePath));
            $this->io->write('');
        }

        $this->io->write('');
        $this->io->write('<info>Done!</info> You can now list the available tasks with: <comment>vendor/bin/castor</comment>');
    }

    private function relativeToCwd(string $path): string
    {
        $cwd = getcwd() ?: '';

        return str_starts_with($path, $cwd) ? ltrim(substr($path, strlen($cwd)), DIRECTORY_SEPARATOR) : $path;
    }
}
